# Generated by Django 5.1.6 on 2025-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="store",
            name="contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="store",
            name="sub_image1",
            field=models.ImageField(blank=True, null=True, upload_to="store_images/"),
        ),
        migrations.AddField(
            model_name="store",
            name="sub_image2",
            field=models.ImageField(blank=True, null=True, upload_to="store_images/"),
        ),
    ]
